node {
 try  {
 notify('Job Started') 
	 
  stage('Git-Checkout') {
  // git branch:'master', url:'https://github.com/imbhascker13/bikenbrands.git'
	 git url:'https://imbhascker13@bitbucket.org/accelerators-devops/bike-showroom-app.git'
  }
   stage('TruffleHog') {
    // sh label: '', script: 'trufflehog --regex --entropy=False https://github.com/imbhascker13/trufflehog.git'
	sh 'trufflehog --regex --entropy=False  https://imbhascker13@bitbucket.org/accelerators-devops/bike-showroom-app.git'  
  }	 
  stage('Input to continue forther') {
   input('git checkout done Do you want to forther proceed?')  
  }
	 
 def project_path="Bikes/"
 dir(project_path) {
    
  stage('Maven-Clean') {
   sh label: '', script: 'mvn clean'
  }
    
 stage('Maven-Compile') {
   sh label: '', script: 'mvn compile'
  }
	 
  stage('Sonar Analysis'){
        withSonarQubeEnv('Sonarqube'){
         sh 'mvn sonar:sonar'
        }
        }
	 
  stage("Quality Gate") {
  timeout(time: 1, unit: 'HOURS') { // Just in case something goes wrong, pipeline will be killed after a timeout
    def qg = waitForQualityGate() // Reuse taskId previously collected by withSonarQubeEnv
    if (qg.status != 'OK') {
      error "Pipeline aborted due to quality gate failure: ${qg.status}"
    }
  }
}
	 
   stage('Maven-Test') {
   sh label: '', script: 'mvn test'
  }
  
   stage('Maven-Package') {
   sh label: '', script: 'mvn package'
  }
  
   stage('Archive-Artifacts') {
   archiveArtifacts 'target/*.war'
  }
  
   stage('Jfrog Artifacory Upload') {
        def server= Artifactory.server 'Artifactory'
                    def uploadSpec= """{
                        "files": [{
                        "pattern": "target/*.war",
                        "target": "petc"}]
                    }"""
        server.upload(uploadSpec)
        
        }
stage('Input for deploy in test server') {  
   input('Do you want to deploy in test server proceed?')      
        }
  stage('Downstream Build -- Docker Deployment'){
	 build 'qa_analysis_for_bikenbrands'
	}
}
notify('Job Completed')   
} catch (err) {
  notify("Error ${err}")
  currentBuild.result = 'FAILURE'
}
}

def notify(status){
    emailext (
	to: "bhaskarreddygbr7@gmail.com",
	subject: "${status}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
	 body: """<p>${status}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
	<p>Check console output at <a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a></p>""",
		)
	}
