node {
 try  {
 notify('Job Started') 

	  stage('Git-Checkout') {
   git branch:'qualityassurance', url:'https://github.com/imbhascker13/bikenbrands.git'
  }
	   stage('Input for deploy in test server') {  
   input('Do you want to deploy in test server proceed?')      
        }
 def project_path="Bikes/"
 
 dir(project_path) {
       stage('Maven-Package') {
   sh label: '', script: 'mvn package'
  }

 
   stage('Docker-Stage-Deployment') {
   sh label: 'DOCKER DEPLOYMENT', script: 'docker-compose up -d --build'
  }
	 

 }
notify('Job Completed')   
} catch (err) {
  notify("Error ${err}")
  currentBuild.result = 'FAILURE'
}
}

def notify(status){
    emailext (
	to: "bhaskarreddygbr7@gmail.com"
	subject: "${status}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
	 body: """<p>${status}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
	<p>Check console output at <a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a></p>""",
		)
	}
